services:
  signal-cli-rest-api:
    image: 'bbernhard/signal-cli-rest-api:0.98'
    environment:
      - MODE=${MODE}
      - AUTO_RECEIVE_SCHEDULE=${AUTO_RECEIVE_SCHEDULE}
      - LOG_LEVEL=${LOG_LEVEL}
      - DEFAULT_SIGNAL_TEXT_MODE=${DEFAULT_SIGNAL_TEXT_MODE}
      - SWAGGER_HOST=${SWAGGER_HOST}
      - SWAGGER_USE_HTTPS_AS_PREFERRED_SCHEME=${SWAGGER_USE_HTTPS_AS_PREFERRED_SCHEME}
      - SIGNAL_CLI_UID=${SIGNAL_CLI_UID}
      - SIGNAL_CLI_GID=${SIGNAL_CLI_GID}
      - SIGNAL_CLI_CHOWN_ON_STARTUP=${SIGNAL_CLI_CHOWN_ON_STARTUP}
      - JSON_RPC_TRUST_NEW_IDENTITIES=${JSON_RPC_TRUST_NEW_IDENTITIES}
      - JSON_RPC_IGNORE_ATTACHMENTS=${JSON_RPC_IGNORE_ATTACHMENTS}
      - JSON_RPC_IGNORE_STORIES=${JSON_RPC_IGNORE_STORIES}
      - JSON_RPC_IGNORE_AVATARS=${JSON_RPC_IGNORE_AVATARS}
      - JSON_RPC_IGNORE_STICKERS=${JSON_RPC_IGNORE_STICKERS}
    volumes:
      - ${APP_DATA_DIR}/data/signal-cli:/home/.local/share/signal-cli
    x-runtipi:
      is_main: true
      internal_port: 8080

x-runtipi:
  schema_version: 2
  overrides: []
